# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renderthreads.ui'
#
# Created: Wed Aug 05 18:05:02 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_wdgt_main(object):
    def setupUi(self, wdgt_main):
        wdgt_main.setObjectName("wdgt_main")
        wdgt_main.resize(268, 461)
        self.verticalLayout = QtGui.QVBoxLayout(wdgt_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wdgt_header_spacer_top = QtGui.QWidget(wdgt_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_header_spacer_top.sizePolicy().hasHeightForWidth())
        self.wdgt_header_spacer_top.setSizePolicy(sizePolicy)
        self.wdgt_header_spacer_top.setMinimumSize(QtCore.QSize(0, 20))
        self.wdgt_header_spacer_top.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wdgt_header_spacer_top.setObjectName("wdgt_header_spacer_top")
        self.verticalLayout.addWidget(self.wdgt_header_spacer_top)
        self.wdgt_header = QtGui.QWidget(wdgt_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_header.sizePolicy().hasHeightForWidth())
        self.wdgt_header.setSizePolicy(sizePolicy)
        self.wdgt_header.setMinimumSize(QtCore.QSize(0, 33))
        self.wdgt_header.setMaximumSize(QtCore.QSize(16777215, 33))
        self.wdgt_header.setObjectName("wdgt_header")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.wdgt_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wdgt_header_spacer_left = QtGui.QWidget(self.wdgt_header)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_header_spacer_left.sizePolicy().hasHeightForWidth())
        self.wdgt_header_spacer_left.setSizePolicy(sizePolicy)
        self.wdgt_header_spacer_left.setObjectName("wdgt_header_spacer_left")
        self.horizontalLayout_2.addWidget(self.wdgt_header_spacer_left)
        self.frm_header_icon = QtGui.QFrame(self.wdgt_header)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_header_icon.sizePolicy().hasHeightForWidth())
        self.frm_header_icon.setSizePolicy(sizePolicy)
        self.frm_header_icon.setMinimumSize(QtCore.QSize(200, 0))
        self.frm_header_icon.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frm_header_icon.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_header_icon.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_header_icon.setObjectName("frm_header_icon")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.frm_header_icon)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.wdgt_header_icon = QtGui.QWidget(self.frm_header_icon)
        self.wdgt_header_icon.setObjectName("wdgt_header_icon")
        self.verticalLayout_28.addWidget(self.wdgt_header_icon)
        self.horizontalLayout_2.addWidget(self.frm_header_icon)
        self.wdgt_header_spacer_right = QtGui.QWidget(self.wdgt_header)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_header_spacer_right.sizePolicy().hasHeightForWidth())
        self.wdgt_header_spacer_right.setSizePolicy(sizePolicy)
        self.wdgt_header_spacer_right.setObjectName("wdgt_header_spacer_right")
        self.horizontalLayout_2.addWidget(self.wdgt_header_spacer_right)
        self.verticalLayout.addWidget(self.wdgt_header)
        self.wdgt_header_spacer_bottom = QtGui.QWidget(wdgt_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_header_spacer_bottom.sizePolicy().hasHeightForWidth())
        self.wdgt_header_spacer_bottom.setSizePolicy(sizePolicy)
        self.wdgt_header_spacer_bottom.setMinimumSize(QtCore.QSize(0, 30))
        self.wdgt_header_spacer_bottom.setMaximumSize(QtCore.QSize(16777215, 30))
        self.wdgt_header_spacer_bottom.setObjectName("wdgt_header_spacer_bottom")
        self.verticalLayout.addWidget(self.wdgt_header_spacer_bottom)
        self.wdgt_stkwdgt_menu = QtGui.QWidget(wdgt_main)
        self.wdgt_stkwdgt_menu.setObjectName("wdgt_stkwdgt_menu")
        self.horizontalLayout = QtGui.QHBoxLayout(self.wdgt_stkwdgt_menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.wdgt_stkwdgt_menu)
        self.stkwdgt_content = QtGui.QStackedWidget(wdgt_main)
        self.stkwdgt_content.setObjectName("stkwdgt_content")
        self.pg_nodes_and_log = QtGui.QWidget()
        self.pg_nodes_and_log.setObjectName("pg_nodes_and_log")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pg_nodes_and_log)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wdgt_nodes_and_log = QtGui.QWidget(self.pg_nodes_and_log)
        self.wdgt_nodes_and_log.setObjectName("wdgt_nodes_and_log")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wdgt_nodes_and_log)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splt_nodes_and_log = QtGui.QSplitter(self.wdgt_nodes_and_log)
        self.splt_nodes_and_log.setLineWidth(0)
        self.splt_nodes_and_log.setMidLineWidth(0)
        self.splt_nodes_and_log.setOrientation(QtCore.Qt.Vertical)
        self.splt_nodes_and_log.setHandleWidth(3)
        self.splt_nodes_and_log.setObjectName("splt_nodes_and_log")
        self.wdgt_nodes = QtGui.QWidget(self.splt_nodes_and_log)
        self.wdgt_nodes.setObjectName("wdgt_nodes")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wdgt_nodes)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frm_nodes_header = QtGui.QFrame(self.wdgt_nodes)
        self.frm_nodes_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_nodes_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_nodes_header.setObjectName("frm_nodes_header")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.frm_nodes_header)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbl_nodes_header = QtGui.QLabel(self.frm_nodes_header)
        self.lbl_nodes_header.setObjectName("lbl_nodes_header")
        self.verticalLayout_16.addWidget(self.lbl_nodes_header)
        self.verticalLayout_5.addWidget(self.frm_nodes_header)
        self.frm_nodes = QtGui.QFrame(self.wdgt_nodes)
        self.frm_nodes.setFrameShape(QtGui.QFrame.Box)
        self.frm_nodes.setFrameShadow(QtGui.QFrame.Plain)
        self.frm_nodes.setObjectName("frm_nodes")
        self.lyt_frm_nodes = QtGui.QVBoxLayout(self.frm_nodes)
        self.lyt_frm_nodes.setObjectName("lyt_frm_nodes")
        self.verticalLayout_5.addWidget(self.frm_nodes)
        self.frm_pbar_render = QtGui.QFrame(self.wdgt_nodes)
        self.frm_pbar_render.setFrameShape(QtGui.QFrame.Box)
        self.frm_pbar_render.setFrameShadow(QtGui.QFrame.Plain)
        self.frm_pbar_render.setObjectName("frm_pbar_render")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.frm_pbar_render)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_5.addWidget(self.frm_pbar_render)
        self.wdgt_splt_space_nodes = QtGui.QWidget(self.wdgt_nodes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_splt_space_nodes.sizePolicy().hasHeightForWidth())
        self.wdgt_splt_space_nodes.setSizePolicy(sizePolicy)
        self.wdgt_splt_space_nodes.setMinimumSize(QtCore.QSize(0, 10))
        self.wdgt_splt_space_nodes.setObjectName("wdgt_splt_space_nodes")
        self.verticalLayout_5.addWidget(self.wdgt_splt_space_nodes)
        self.wdgt_log = QtGui.QWidget(self.splt_nodes_and_log)
        self.wdgt_log.setObjectName("wdgt_log")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.wdgt_log)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.wdgt_splt_space_log = QtGui.QWidget(self.wdgt_log)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_splt_space_log.sizePolicy().hasHeightForWidth())
        self.wdgt_splt_space_log.setSizePolicy(sizePolicy)
        self.wdgt_splt_space_log.setMinimumSize(QtCore.QSize(0, 10))
        self.wdgt_splt_space_log.setObjectName("wdgt_splt_space_log")
        self.verticalLayout_9.addWidget(self.wdgt_splt_space_log)
        self.frm_log_header = QtGui.QFrame(self.wdgt_log)
        self.frm_log_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_log_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_log_header.setObjectName("frm_log_header")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.frm_log_header)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lbl_log_header = QtGui.QLabel(self.frm_log_header)
        self.lbl_log_header.setObjectName("lbl_log_header")
        self.verticalLayout_17.addWidget(self.lbl_log_header)
        self.verticalLayout_9.addWidget(self.frm_log_header)
        self.frm_log_text_edit = QtGui.QFrame(self.wdgt_log)
        self.frm_log_text_edit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_log_text_edit.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_log_text_edit.setObjectName("frm_log_text_edit")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.frm_log_text_edit)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.te_log = QtGui.QTextEdit(self.frm_log_text_edit)
        self.te_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.te_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.te_log.setReadOnly(False)
        self.te_log.setObjectName("te_log")
        self.verticalLayout_18.addWidget(self.te_log)
        self.verticalLayout_9.addWidget(self.frm_log_text_edit)
        self.verticalLayout_4.addWidget(self.splt_nodes_and_log)
        self.verticalLayout_3.addWidget(self.wdgt_nodes_and_log)
        self.stkwdgt_content.addWidget(self.pg_nodes_and_log)
        self.pg_threads = QtGui.QWidget()
        self.pg_threads.setObjectName("pg_threads")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.pg_threads)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.sa_threads = QtGui.QScrollArea(self.pg_threads)
        self.sa_threads.setFrameShape(QtGui.QFrame.NoFrame)
        self.sa_threads.setFrameShadow(QtGui.QFrame.Plain)
        self.sa_threads.setLineWidth(0)
        self.sa_threads.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sa_threads.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sa_threads.setWidgetResizable(True)
        self.sa_threads.setObjectName("sa_threads")
        self.sawdgt_threads_options = QtGui.QWidget()
        self.sawdgt_threads_options.setGeometry(QtCore.QRect(0, 0, 240, 354))
        self.sawdgt_threads_options.setObjectName("sawdgt_threads_options")
        self.lyt_sawdgt_threads = QtGui.QVBoxLayout(self.sawdgt_threads_options)
        self.lyt_sawdgt_threads.setObjectName("lyt_sawdgt_threads")
        self.frm_threads_options = QtGui.QFrame(self.sawdgt_threads_options)
        self.frm_threads_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_threads_options.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_threads_options.setObjectName("frm_threads_options")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frm_threads_options)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.wdgt_threads = QtGui.QWidget(self.frm_threads_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_threads.sizePolicy().hasHeightForWidth())
        self.wdgt_threads.setSizePolicy(sizePolicy)
        self.wdgt_threads.setObjectName("wdgt_threads")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.wdgt_threads)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frm_threads_header = QtGui.QFrame(self.wdgt_threads)
        self.frm_threads_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_threads_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_threads_header.setObjectName("frm_threads_header")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frm_threads_header)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_threads_header = QtGui.QLabel(self.frm_threads_header)
        self.lbl_threads_header.setObjectName("lbl_threads_header")
        self.verticalLayout_6.addWidget(self.lbl_threads_header)
        self.verticalLayout_14.addWidget(self.frm_threads_header)
        self.frm_threads = QtGui.QFrame(self.wdgt_threads)
        self.frm_threads.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_threads.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_threads.setObjectName("frm_threads")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frm_threads)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_14.addWidget(self.frm_threads)
        self.verticalLayout_11.addWidget(self.wdgt_threads)
        self.wdgt_threads_queue_space = QtGui.QWidget(self.frm_threads_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_threads_queue_space.sizePolicy().hasHeightForWidth())
        self.wdgt_threads_queue_space.setSizePolicy(sizePolicy)
        self.wdgt_threads_queue_space.setMinimumSize(QtCore.QSize(0, 10))
        self.wdgt_threads_queue_space.setObjectName("wdgt_threads_queue_space")
        self.verticalLayout_11.addWidget(self.wdgt_threads_queue_space)
        self.wdgt_queue = QtGui.QWidget(self.frm_threads_options)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_queue.sizePolicy().hasHeightForWidth())
        self.wdgt_queue.setSizePolicy(sizePolicy)
        self.wdgt_queue.setObjectName("wdgt_queue")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.wdgt_queue)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frm_queue_header = QtGui.QFrame(self.wdgt_queue)
        self.frm_queue_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_queue_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_queue_header.setObjectName("frm_queue_header")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frm_queue_header)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_queue_header = QtGui.QLabel(self.frm_queue_header)
        self.lbl_queue_header.setObjectName("lbl_queue_header")
        self.verticalLayout_8.addWidget(self.lbl_queue_header)
        self.verticalLayout_13.addWidget(self.frm_queue_header)
        self.frm_queue = QtGui.QFrame(self.wdgt_queue)
        self.frm_queue.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_queue.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_queue.setObjectName("frm_queue")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frm_queue)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_13.addWidget(self.frm_queue)
        self.verticalLayout_11.addWidget(self.wdgt_queue)
        self.lyt_sawdgt_threads.addWidget(self.frm_threads_options)
        self.sa_threads.setWidget(self.sawdgt_threads_options)
        self.verticalLayout_12.addWidget(self.sa_threads)
        self.stkwdgt_content.addWidget(self.pg_threads)
        self.pg_command_line = QtGui.QWidget()
        self.pg_command_line.setObjectName("pg_command_line")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.pg_command_line)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.sa_command_line = QtGui.QScrollArea(self.pg_command_line)
        self.sa_command_line.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sa_command_line.setWidgetResizable(True)
        self.sa_command_line.setObjectName("sa_command_line")
        self.sawdgt_command_line = QtGui.QWidget()
        self.sawdgt_command_line.setGeometry(QtCore.QRect(0, 0, 149, 252))
        self.sawdgt_command_line.setObjectName("sawdgt_command_line")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.sawdgt_command_line)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_command_line_complete = QtGui.QFrame(self.sawdgt_command_line)
        self.frm_command_line_complete.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_command_line_complete.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_command_line_complete.setObjectName("frm_command_line_complete")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.frm_command_line_complete)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.wdgt_command_line = QtGui.QWidget(self.frm_command_line_complete)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_command_line.sizePolicy().hasHeightForWidth())
        self.wdgt_command_line.setSizePolicy(sizePolicy)
        self.wdgt_command_line.setObjectName("wdgt_command_line")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.wdgt_command_line)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frm_command_line_header = QtGui.QFrame(self.wdgt_command_line)
        self.frm_command_line_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_command_line_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_command_line_header.setObjectName("frm_command_line_header")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.frm_command_line_header)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lbl_command_line_header = QtGui.QLabel(self.frm_command_line_header)
        self.lbl_command_line_header.setObjectName("lbl_command_line_header")
        self.verticalLayout_22.addWidget(self.lbl_command_line_header)
        self.verticalLayout_21.addWidget(self.frm_command_line_header)
        self.frm_command_line = QtGui.QFrame(self.wdgt_command_line)
        self.frm_command_line.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_command_line.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_command_line.setObjectName("frm_command_line")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.frm_command_line)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_21.addWidget(self.frm_command_line)
        self.frm_command_line_options = QtGui.QFrame(self.wdgt_command_line)
        self.frm_command_line_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_command_line_options.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_command_line_options.setObjectName("frm_command_line_options")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.frm_command_line_options)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_21.addWidget(self.frm_command_line_options)
        self.verticalLayout_20.addWidget(self.wdgt_command_line)
        self.wdgt_command_line_and_constants_space = QtGui.QWidget(self.frm_command_line_complete)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_command_line_and_constants_space.sizePolicy().hasHeightForWidth())
        self.wdgt_command_line_and_constants_space.setSizePolicy(sizePolicy)
        self.wdgt_command_line_and_constants_space.setMinimumSize(QtCore.QSize(0, 10))
        self.wdgt_command_line_and_constants_space.setObjectName("wdgt_command_line_and_constants_space")
        self.verticalLayout_20.addWidget(self.wdgt_command_line_and_constants_space)
        self.wdgt_constants = QtGui.QWidget(self.frm_command_line_complete)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgt_constants.sizePolicy().hasHeightForWidth())
        self.wdgt_constants.setSizePolicy(sizePolicy)
        self.wdgt_constants.setObjectName("wdgt_constants")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.wdgt_constants)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frm_constants_header = QtGui.QFrame(self.wdgt_constants)
        self.frm_constants_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_constants_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_constants_header.setObjectName("frm_constants_header")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.frm_constants_header)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.lbl_constants_header = QtGui.QLabel(self.frm_constants_header)
        self.lbl_constants_header.setObjectName("lbl_constants_header")
        self.verticalLayout_25.addWidget(self.lbl_constants_header)
        self.verticalLayout_24.addWidget(self.frm_constants_header)
        self.frm_constants = QtGui.QFrame(self.wdgt_constants)
        self.frm_constants.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_constants.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_constants.setObjectName("frm_constants")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.frm_constants)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_24.addWidget(self.frm_constants)
        self.verticalLayout_20.addWidget(self.wdgt_constants)
        self.verticalLayout_2.addWidget(self.frm_command_line_complete)
        self.sa_command_line.setWidget(self.sawdgt_command_line)
        self.verticalLayout_19.addWidget(self.sa_command_line)
        self.stkwdgt_content.addWidget(self.pg_command_line)
        self.pg_options = QtGui.QWidget()
        self.pg_options.setObjectName("pg_options")
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.pg_options)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.sa_options = QtGui.QScrollArea(self.pg_options)
        self.sa_options.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sa_options.setWidgetResizable(True)
        self.sa_options.setObjectName("sa_options")
        self.sawdgt_options = QtGui.QWidget()
        self.sawdgt_options.setGeometry(QtCore.QRect(0, 0, 117, 121))
        self.sawdgt_options.setObjectName("sawdgt_options")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.sawdgt_options)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frm_options = QtGui.QFrame(self.sawdgt_options)
        self.frm_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_options.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_options.setObjectName("frm_options")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.frm_options)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.wdgt_general_options = QtGui.QWidget(self.frm_options)
        self.wdgt_general_options.setObjectName("wdgt_general_options")
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.wdgt_general_options)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.frm_general_options_header = QtGui.QFrame(self.wdgt_general_options)
        self.frm_general_options_header.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_general_options_header.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_general_options_header.setObjectName("frm_general_options_header")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.frm_general_options_header)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.lbl_general_options_header = QtGui.QLabel(self.frm_general_options_header)
        self.lbl_general_options_header.setObjectName("lbl_general_options_header")
        self.verticalLayout_34.addWidget(self.lbl_general_options_header)
        self.verticalLayout_33.addWidget(self.frm_general_options_header)
        self.frm_general_options = QtGui.QFrame(self.wdgt_general_options)
        self.frm_general_options.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_general_options.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_general_options.setObjectName("frm_general_options")
        self.verticalLayout_35 = QtGui.QVBoxLayout(self.frm_general_options)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_33.addWidget(self.frm_general_options)
        self.verticalLayout_36.addWidget(self.wdgt_general_options)
        self.verticalLayout_32.addWidget(self.frm_options)
        self.sa_options.setWidget(self.sawdgt_options)
        self.verticalLayout_31.addWidget(self.sa_options)
        self.stkwdgt_content.addWidget(self.pg_options)
        self.verticalLayout.addWidget(self.stkwdgt_content)

        self.retranslateUi(wdgt_main)
        self.stkwdgt_content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(wdgt_main)

    def retranslateUi(self, wdgt_main):
        wdgt_main.setWindowTitle(QtGui.QApplication.translate("wdgt_main", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_nodes_header.setText(QtGui.QApplication.translate("wdgt_main", "Write Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_log_header.setText(QtGui.QApplication.translate("wdgt_main", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_threads_header.setText(QtGui.QApplication.translate("wdgt_main", "Threads", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_queue_header.setText(QtGui.QApplication.translate("wdgt_main", "Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_command_line_header.setText(QtGui.QApplication.translate("wdgt_main", "Command Line", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_constants_header.setText(QtGui.QApplication.translate("wdgt_main", "Constants", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_general_options_header.setText(QtGui.QApplication.translate("wdgt_main", "General", None, QtGui.QApplication.UnicodeUTF8))

